### ISSUE TITLE
"Could not read field headers" with specific body

### ISSUE THREAD

**Issue by dariost** [abonander/multipart#86] opened 2017-07-26 14:32 UTC
I have an application built with Rocket which let the users upload files via a form using the multipart format.
It has more than 100 successful uploads, but there is a single file which triggers the "Could not read field headers" error. I've uploaded this file with a simple use of multipart (it is entirely possibile that I'm using multipart in a wrong way) [test_error.zip](https://github.com/abonander/multipart/files/1176893/test_error.zip) and giving a `cargo run` results in
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: InvalidData, error: Other("Could not read field headers") }) }', /checkout/src/libcore/result.rs:860:4
```
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=47624485)](https://www.bountysource.com/issues/47624485-could-not-read-field-headers-with-specific-body?utm_source=47624485&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by abonander** [comment] 2017-07-26 17:58
That error message is returned here:

https://github.com/abonander/multipart/blob/master/src/server/field.rs#L53

Which suggests that the field headers for that file in a multipart request don't fit in an 8K (!) buffer. 

However, can you verify what version of `multipart` you're using? The formatting of error messages is different in the most recent version.

**Comment by dariost** [comment] 2017-07-26 18:19
I'm using the latest git version (commit aed39628), but I've tried also with 1.13.1 and 1.12.0 with the same result.

Additional info which might be useful: this multipart body was generated by Firefox Nightly (56.0a 2017/07/26) and I'm using rustc 1.21.0-nightly (c417ee9ae 2017-07-25) (but I've also tried with rustc 1.19.0 which gives the same result)

**Comment by abonander** [comment] 2017-07-26 18:56
That's funny how it changes the error message, it should be a lot noisier, honestly. (And the error message could be better). 

The test project and dump is very helpful. I thought the zip file was the one actually giving you the problems so that saves me from having to reproduce it.

So even with the file contents removed, this still produces an error:

```
-----------------------------3561323961828871014444412781
Content-Disposition: form-data; name="partecipation"; filename="SOLABL2_lez4_1617.pdf"
Content-Type: application/pdf

-----------------------------3561323961828871014444412781--
```

I should be able to work with this to figure out what's going wrong.

**Comment by abonander** [comment] 2017-07-26 23:33
So the problem is that the boundary you're passing has the `--` prepended that the spec wants, but `multipart` automatically prepends this too, so the boundary it's looking for has two more hyphens than actually appear in the request body. It's so difficult to see because of all the rest of the hyphens being used as padding characters (who knows why they decided to do that). 

This is causing `multipart` to skip the entire request body and try to read headers from an empty buffer, which is a logic error on my part; if it sees an empty buffer it should just return no entries, though this would probably be just as confusing. I'm thinking of adding a log warning when the given boundary already starts with `--` but that might just add noise to logs because of the aforementioned.

**Comment by dariost** [comment] 2017-08-01 13:55
Just letting you know I posted a bounty for this issue

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=47624485)](https://www.bountysource.com/issues/47624485-could-not-read-field-headers-with-specific-body?utm_source=47624485&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by abonander** [comment] 2017-08-01 21:03
I do already have a fix for this on the `0.13` branch, though if you still prepend the `--` now it just produces *no* entries because it can't find the boundary. I also added a note to `Multipart::with_body()` about it. I just forgot to publish an update.

**Comment by dariost** [comment] 2017-08-01 22:19
I'm using the latest commit of branch "0.13", but there seems to be another problem: I've made another example ([test_error2.zip](https://github.com/abonander/multipart/files/1192099/test_error2.zip)), this time the boundary is correct (it hasn't the `--` prepended) but it still gives no entries (it doesn't print `An entry!` even if there is one)

**Comment by abonander** [comment] 2017-08-01 22:37
Yeah, looks like I introduced a logic bug, weird cause it was working when I tested it the first time.

**Comment by dariost** [comment] 2017-08-01 22:45
Also, another thing I found out that happens when using the latest commit from branch "master", for some reason this ([test_error3.zip](https://github.com/abonander/multipart/files/1192155/test_error3.zip)) example panics, even if the multipart is valid and the boundary is correct

**Closed** 2017-08-05 18:03 UTC
Labels: bug
