### ISSUE TITLE
Content-Disposition does not need to be the first entry

### ISSUE THREAD

**Issue by Drakulix** [abonander/multipart#51] opened 2016-10-17 14:10 UTC
As the title states multipart/form-data does not specify that Content-Disposition needs to be the first field in a request. The optional Content-Type might also be the first one.

Relevant Sections of the RFC:
https://tools.ietf.org/html/rfc2388#section-3
https://tools.ietf.org/html/rfc2388#section-5.5

multipart's inability to handle such requests recently caused brackage in one of my projects:
https://github.com/MPIB/hazel/issues/5

As a result of one of the primary clients changing its default order:
https://github.com/NuGet/Home/issues/2661

multipart is an indirect dependency via https://github.com/iron/params in my project and although I am using a currently outdated version (0.7), I do not think this issue can be resolved by updating my dependencies after looking at your source code:

https://docs.rs/multipart/0.8.0/src/multipart/.cargo/registry/src/github.com-1ecc6299db9ec823/multipart-0.8.0/src/server/mod.rs.html#427

**Comment by abonander** [comment] 2016-10-18 04:42
@Drakulix Please clone the `httparse` branch and [override the dependency in your Cargo configuration](http://doc.crates.io/config.html) to see if it's fixed. This branch should not depend on the ordering of the headers anymore. It may throw an error if there are more than 4 headers per field, however. If you know how many different headers can appear, I can adjust that number.

**Comment by Drakulix** [comment] 2016-10-18 08:25
Thank you very much for that really quick fix.
I will try this out most likely today, altough I might have to update some dependencies to be compatible with multipart 0.9 (currently on 0.7).

Four headers should be far more then required, I will open a seperate issue for this, if it ever becomes a problem.

**Comment by Drakulix** [comment] 2016-10-18 16:31
Alright so I did an override I now if the order is reversed (old client still works), it loops over and over without finishing parsing, so I had to kill the server eventually.

Here is the end of the log, it really is all the same.
```
16:29:25 [DEBUG] multipart::server::boundary: After-loop Buf len: 144 Search idx: 123 Boundary read: false
16:29:25 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:101] - Returning buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf"
16:29:25 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:47] - Buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf-8\'\'package.nupkg\r\n\r\n"
16:29:25 [DEBUG] multipart::server::boundary: Before-loop Buf len: 144 Search idx: 123 Boundary read: false
16:29:25 [DEBUG] multipart::server::boundary: maybe_boundary: Some(0)
16:29:25 [DEBUG] multipart::server::boundary: After-loop Buf len: 144 Search idx: 123 Boundary read: false
16:29:25 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:101] - Returning buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf"
16:29:25 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:47] - Buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf-8\'\'package.nupkg\r\n\r\n"
16:29:25 [DEBUG] multipart::server::boundary: Before-loop Buf len: 144 Search idx: 123 Boundary read: false
16:29:25 [DEBUG] multipart::server::boundary: maybe_boundary: Some(0)
16:29:25 [DEBUG] multipart::server::boundary: After-loop Buf len: 144 Search idx: 123 Boundary read: false
16:29:25 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:101] - Returning buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf"
16:29:25 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:47] - Buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf-8\'\'package.nupkg\r\n\r\n"
16:29:25 [DEBUG] multipart::server::boundary: Before-loop Buf len: 144 Search idx: 123 Boundary read: false
16:29:25 [DEBUG] multipart::server::boundary: maybe_boundary: Some(0)
16:29:25 [DEBUG] multipart::server::boundary: After-loop Buf len: 144 Search idx: 123 Boundary read: false
```

**Comment by abonander** [comment] 2016-10-18 21:44
The problem now is that the values of `name` and `filename` aren't quoted, which isn't what I expected. I can fix this but I would consider the Nuget client barely compliant here, it's doing some weird things.

**Comment by abonander** [comment] 2016-10-18 22:22
[RFC 7578](https://tools.ietf.org/html/rfc7578), section 4.2 continued on page 5:

> NOTE: The encoding method described in [RFC5987], which would add a
   "filename*" parameter to the Content-Disposition header field, MUST
   NOT be used.

That key is easy enough to ignore though. Not quoting the other parameter value strings I would consider to be non-conformant.

**Comment by abonander** [comment] 2016-10-19 01:11
Do `git pull` on your local copy and try again please.

**Comment by Drakulix** [comment] 2016-10-19 07:16
I am sad to tell you, that it still loops:
```
07:11:12 [DEBUG] multipart::server::boundary: maybe_boundary: Some(0)
07:11:12 [DEBUG] multipart::server::boundary: After-loop Buf len: 144 Search idx: 123 Boundary read: false
07:11:12 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:101] - Returning buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf"
07:11:12 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:47] - Buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf-8\'\'package.nupkg\r\n\r\n"
07:11:12 [DEBUG] multipart::server::boundary: Before-loop Buf len: 144 Search idx: 123 Boundary read: false
07:11:12 [DEBUG] multipart::server::boundary: maybe_boundary: Some(0)
07:11:12 [DEBUG] multipart::server::boundary: After-loop Buf len: 144 Search idx: 123 Boundary read: false
07:11:12 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:101] - Returning buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf"
07:11:12 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:47] - Buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf-8\'\'package.nupkg\r\n\r\n"
07:11:12 [DEBUG] multipart::server::boundary: Before-loop Buf len: 144 Search idx: 123 Boundary read: false
07:11:12 [DEBUG] multipart::server::boundary: maybe_boundary: Some(0)
07:11:12 [DEBUG] multipart::server::boundary: After-loop Buf len: 144 Search idx: 123 Boundary read: false
07:11:12 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:101] - Returning buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf"
07:11:12 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:47] - Buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf-8\'\'package.nupkg\r\n\r\n"
07:11:12 [DEBUG] multipart::server::boundary: Before-loop Buf len: 144 Search idx: 123 Boundary read: false
```

Also the nuget client does a lot of very weird stuff (not limited to the HTTP requests), so I totally understand, if you would not want to support and non-conformant client. I was just hoping, that I would not have to open an issue on nuget, because that would likely take years to get accepted, which would mean, that I would have to fork multipart to get this working for my project again in the meantime.

**Comment by abonander** [comment] 2016-10-19 07:38
This may be a bug in the boundary parser cause half of the loop has a dash at the end, which is what it's looking for as the start of a boundary in the request body. It's probably not skipping hyphens correctly.

**Comment by abonander** [comment] 2016-10-19 07:42
I can't really push a commit because my Internet is down, but maybe you can try this fix for me. At line 75 in `src/server/boundary.rs` add a `+ 1` to the end of that expression and see if it fixes it. Off-by-one errors are a major source of bugs in this crate.

**Comment by Drakulix** [comment] 2016-10-19 07:46
Are you sure that you mean line 75? That one only contains a break:
https://github.com/abonander/multipart/blob/master/src/server/boundary.rs#L75

**Comment by abonander** [comment] 2016-10-19 08:02
That's `master`, not the `httparse` branch which you should be on. Anyway, my Internet came back up so I added the fix plus a test for it. It shouldn't be looping now.

**Comment by Drakulix** [comment] 2016-10-19 08:04
Yes that link was master, but it is actually the same line on httparse https://github.com/abonander/multipart/blob/httparse/src/server/boundary.rs#L75

anyway trying now

**Comment by abonander** [comment] 2016-10-19 08:17
Yeah I meant line 71, sorry.

**Comment by Drakulix** [comment] 2016-10-19 08:29
Still:

```
08:27:52 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:101] - Returning buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf"
08:27:52 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:47] - Buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf-8\'\'package.nupkg\r\n\r\n"
08:27:52 [DEBUG] multipart::server::boundary: Before-loop Buf len: 144 Search idx: 123 Boundary read: false
08:27:52 [DEBUG] multipart::server::boundary: maybe_boundary: Some(0)
08:27:52 [DEBUG] multipart::server::boundary: After-loop Buf len: 144 Search idx: 123 Boundary read: false
08:27:52 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:101] - Returning buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf"
08:27:52 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:47] - Buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf-8\'\'package.nupkg\r\n\r\n"
08:27:52 [DEBUG] multipart::server::boundary: Before-loop Buf len: 144 Search idx: 123 Boundary read: false
08:27:52 [DEBUG] multipart::server::boundary: maybe_boundary: Some(0)
08:27:52 [DEBUG] multipart::server::boundary: After-loop Buf len: 144 Search idx: 123 Boundary read: false
```

Do you need some test data to reproduce this yourself? Or do we want to continue like this? :smile:

**Comment by abonander** [comment] 2016-10-19 09:23
Yes please, because I can't figure out what would be causing the problem at this point. Just the raw body of the problematic request will do.

**Comment by Drakulix** [comment] 2016-10-19 20:58
Alright, this took a while as nuget is really picky until it finally sends the problematic request.
This dump should(!) be right. https://drive.google.com/open?id=0B4_MQl2ldbOzZHFqX3JqakVsM0U

**Comment by abonander** [comment] 2016-11-11 02:19
@Drakulix Sorry, forgot about this for a while. I think I've got it fixed with your test file. Can you try the newest revision of the `httparse` branch? I've also made a test binary that makes it easier to debug when you have a request body, just try the following with your test file:

    cargo run --bin test_multipart 4c396c90-ce20-4147-b8c3-95b1ec179e2e dump.bin

**Comment by Drakulix** [comment] 2016-11-14 13:07
Alright. You are right the dump works with this test. The server still does loop however. So I guess my dump is not correct or incomplete. I have no clue how I could get a better one.
Do you have another idea, how we could test this? (This issue is annoying...)
```
12:57:03 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:47] - Buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf-8\'\'package.nupkg\r\n\r\n"
12:57:03 [DEBUG] multipart::server::boundary: Before-loop Buf len: 144 Search idx: 123 Boundary read: false
12:57:03 [DEBUG] multipart::server::boundary: After-loop Buf len: 144 Search idx: 123 Boundary read: false
12:57:03 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:106] - Returning buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf"
12:57:03 [TRACE] multipart::server::boundary: [multipart/src/server/boundary.rs:47] - Buf: "Content-Type: application/octet-stream\r\nContent-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf-8\'\'package.nupkg\r\n\r\n"
12:57:03 [DEBUG] multipart::server::boundary: Before-loop Buf len: 144 Search idx: 123 Boundary read: false
12:57:03 [DEBUG] multipart::server::boundary: After-loop Buf len: 144 Search idx: 123 Boundary read: false
```

**Comment by abonander** [comment] 2016-11-14 16:34
@Drakulix I think I may be onto the problem, here's something to try:

At `src/server/boundary.rs:44`, replace that line with the following:

            let buf = try!(fill_buf_min(&mut self.buf, self.search_idx + (self.boundary.len() * 2)));

And for correctness' sake, revert the change we did at line 75, so change it back to:

    self.search_idx += idx;

I realized that the problem isn't appearing in my local test because the whole file is read into the buffer at once, whereas over the network, data is going to arrive in chunks. It's not properly forcing reads into the buffer, so it just spins its wheels with not enough bytes to decide whether or not it's found a boundary.

**Comment by Drakulix** [comment] 2016-11-15 09:55
Okay now we are onto something.
It finally finishes parsing but then panics with:
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 8192 but the index is 8192', ../src/libcollections/vec.rs:1274
```
Iron catches this panic, but I will try to get a full stack trace for you. It looks just like another off-by-one error.

**Comment by abonander** [comment] 2016-11-15 09:57
I have an idea of where it's at but yeah, backtrace if you can please. I've had a lot of trouble with off-by-ones in this crate.

**Comment by Drakulix** [comment] 2016-11-15 10:00
```
 7:     0x55e47dd50a21 - rust_begin_unwind
   8:     0x55e47dd8d3bf - core::panicking::panic_fmt::hbfc935564d134c1b
   9:     0x55e47dd8d363 - core::panicking::panic_bounds_check::h08d619adcd972898
  10:     0x55e47db77d47 - _<multipart..server..boundary..BoundaryReader<R>>::read_to_boundary::hb1edf81e8b1742a5
  11:     0x55e47db81ced - params::try_parse_multipart::h12ad7a9665e9a3df
  12:     0x55e47db7deef - _<params..Params as plugin..Plugin<iron..request..Request<'a, 'b>>>::eval::h4060d86f3de07a46
  13:     0x55e47dabe2cb - plugin::Pluggable::get_ref::h09d47ebbc937686e
```
Getting line number seems to be harder with iron wrapping the panic but still doable. Is this sufficient enough to track it down?

**Comment by abonander** [comment] 2016-11-15 10:02
Yeah there's not too many places I index a vector there, I'll just make sure they're all properly bounds-checked.

**Comment by abonander** [comment] 2016-11-19 01:07
@Drakulix I'm actually having trouble finding where an index would be out-of-bounds; are you sure you updated line 75? If that was left as-is then it could cause a bounds check failure, but other than that I really have no idea.

**Comment by abonander** [comment] 2016-11-19 01:13
If `self.boundary` is empty then line 61 would trigger a bounds-check assertion, but that would point to a bug somewhere else. Do you want to try adding the following at `src/server/mod.rs:86` between the `match` and the last statement of that block:

    assert!(!boundary.is_empty(), "Request provided a boundary string, but it was empty!");

**Comment by abonander** [comment] 2016-11-19 01:16
@Drakulix The reason you're not getting line numbers is probably because you're compiling without debug information, is that right? Are you just using `cargo build --release`? If so, you can add debug info back in by adding the following to your `Cargo.toml`:

    [profile.release]
    debug = true

**Comment by Drakulix** [comment] 2016-11-21 11:27
I just checked to be sure and of course you are right and I did a release build...

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 8192 but the index is 8192', ../src/libcollections/vec.rs:1274
stack backtrace:
   1:     0x562e84096209 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
   2:     0x562e8409bc1c - std::panicking::default_hook::_{{closure}}::h7b8a142818383fb8
   3:     0x562e8409ae69 - std::panicking::default_hook::h41cf296f654245d7
   4:     0x562e8409b558 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
   5:     0x562e8409b3b2 - std::panicking::begin_panic::h93672d0313d5e8e9
   6:     0x562e8409b320 - std::panicking::begin_panic_fmt::hd0daa02942245d81
   7:     0x562e8409b2a1 - rust_begin_unwind
   8:     0x562e840d7c3f - core::panicking::panic_fmt::hbfc935564d134c1b
   9:     0x562e840d7be3 - core::panicking::panic_bounds_check::h08d619adcd972898
  10:     0x562e8394704e - _<collections..vec..Vec<T> as core..ops..IndexMut<usize>>::index_mut::h969981f640494f5b
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcollections/vec.rs:1274
  11:     0x562e8394d497 - buf_redux::Buffer::read_from::h87dbb2a3eac00f45
                        at /work/target/.cargo/registry/src/github.com-1ecc6299db9ec823/buf_redux-0.3.0/src/lib.rs:482
  12:     0x562e839275da - _<buf_redux..BufReader<R, Rs, Ms>>::read_into_buf::h8756c3d44e7962e5
                        at /work/target/.cargo/registry/src/github.com-1ecc6299db9ec823/buf_redux-0.3.0/src/lib.rs:237
  13:     0x562e8394e6fb - multipart::server::boundary::fill_buf_min::h92557db176906ab0
                        at /work/multipart/src/server/boundary.rs:180
  14:     0x562e83929c1d - _<multipart..server..boundary..BoundaryReader<R>>::read_to_boundary::hb1edf81e8b1742a5
                        at /work/multipart/src/server/boundary.rs:44
  15:     0x562e83947b5d - _<multipart..server..boundary..BoundaryReader<R> as std..io..Read>::read::ha37758e91d1257e4
                        at /work/multipart/src/server/boundary.rs:153
  16:     0x562e8391025a - std::io::util::copy::h790c4bda76dc6d89
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/io/util.rs:52
  17:     0x562e83958a03 - _<multipart..server..MultipartFile<'a, B>>::save_to::_{{closure}}::h2a8232404d5f9193
  18:     0x562e8394d78c - multipart::server::retry_on_interrupt::h0be2d555bf851ad9
                        at /work/multipart/src/server/mod.rs:676
  19:     0x562e8392d96f - _<multipart..server..MultipartFile<'a, B>>::save_to::h70a830d35441e21f
                        at /work/multipart/src/server/mod.rs:436
  20:     0x562e8392d485 - _<multipart..server..MultipartFile<'a, B>>::save_as::ha06d7c4f88aa8a47
                        at /work/multipart/src/server/mod.rs:457
  21:     0x562e8392d8ba - _<multipart..server..MultipartFile<'a, B>>::save_in::hae8c03ea5e0d0b19
                        at /work/multipart/src/server/mod.rs:476
  22:     0x562e839136a1 - _<multipart..server..Multipart<B>>::read_to_entries::h228f3da6023d7ea7
                        at /work/multipart/src/server/mod.rs:218
  23:     0x562e83914a40 - _<multipart..server..Multipart<B>>::save_all::h62bcd9d45bbeea5b
                        at /work/multipart/src/server/mod.rs:150
  24:     0x562e839539a8 - params::try_parse_multipart::h12ad7a9665e9a3df
                        at /work/target/.cargo/registry/src/github.com-1ecc6299db9ec823/params-0.2.2/src/lib.rs:590
  25:     0x562e839517f8 - _<params..Params as plugin..Plugin<iron..request..Request<'a, 'b>>>::eval::h4060d86f3de07a46
```

**Comment by abonander** [comment] 2016-11-21 11:57
@Drakulix So the panic actually started in `buf_redux`! That would have been good to know, haha.

Because of inlining (which is completely LLVM's doing, I don't have any `#[inline]` directives on non-trivial functions in that crate), functions in `buf_redux` were completely excluded from the stack trace! With debug information, however, the full stack trace can be reconstructed by the unwinder.

I see what the problem is, it's a logic error that's kind of littered throughout the crate. The tail cursor (the `end` field of `Buffer`) is often used as an index or a start point in slicing the buffer, which is a problem if the tail cursor is at the end of the buffer! The only tests I have in the crate are copied from the stdlib, so I had no idea what happens when you try to read into a full buffer. Now I know.

**Comment by abonander** [comment] 2016-11-21 12:08
So this is actually already fixed in my latest release of `buf_redux`, since I don't do zeroing the exact same way anymore. It's been fixed for a while, but I forgot to publish the 0.4 release and went straight to 0.5.

Anyway, I've added a regression test against this problem. Try changing the `buf_redux` dependency to `0.5.0` and see if it still panics.

**Comment by abonander** [comment] 2016-11-21 12:46
Alternatively, I have just published `0.9.0-alpha.3` with the updated version. Also please do a `cargo update` as I fixed another bug down the line in the process but it only required a minor version bump so it may not propagate through dependencies immediately.

**Comment by abonander** [comment] 2016-11-21 13:00
Actually, make that `0.9.0-alpha.4`. There was an error in `src/server/iron.rs` that I didn't catch before publishing, and didn't stop the publishing process because `iron` isn't a default feature, but which Travis-CI caught for me (whew!).

**Comment by Drakulix** [comment] 2016-11-21 14:32
Alright. Now I get an error when I unwrap the Params object, which seems to originate in multipart:
`IoError(Error { repr: Custom(Custom { kind: Other, error: StringError("early eof") }) })`

The reason I believe this is multiparts fault, is that it seems to fail to detect the boundary.
Here is the application log (nuget does three requests, until it gives up):
http://pastebin.com/msL18A9m

**Comment by abonander** [comment] 2016-11-21 14:48
I actually think it's a logic error in Hyper's request type where it doesn't like reading into a zero-length slice. I can solve that with a patch to `buf_redux` since it's functionally the same.

**Comment by abonander** [comment] 2016-11-21 14:56
@Drakulix Please run `cargo update` and try again.

**Comment by Drakulix** [comment] 2016-12-06 10:28
Not sure what the latest state is, but this happens with the last commit from the httparse branch.

[hazel.txt](https://github.com/abonander/multipart/files/633544/hazel.txt)

**Comment by abonander** [comment] 2016-12-07 04:11
@Drakulix Did you run `cargo update` before building? I see the panic but I believe I fixed the problem already:

```
10:15:33 [TRACE] hyper::http::h1: [target/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.8.1/src/http/h1.rs:554] - Sized read, remaining=8453415
10:15:33 [TRACE] hyper::http::h1: [target/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.8.1/src/http/h1.rs:560] - Sized read: 0
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Custom(Custom { kind: Other, error: StringError("early eof") }) })', ../src/libcore/result.rs:788
```

The problem with zero-sized reads should have been fixed in my last update to `buf_redux`.

 Please add `RUST_BACKTRACE=1` to your environment variables so we can get the backtrace.

**Comment by Drakulix** [comment] 2016-12-13 09:33
Next try (now definitely with the latest versions).
nuget does 3 request, every one is failing with an internal server error because of a panic.


[hazel.txt](https://github.com/abonander/multipart/files/648451/hazel.txt)

**Comment by abonander** [comment] 2016-12-14 09:31
Yeah, when adding some randomness to my local tests, I've found that my implementation isn't all that robust. I'm working on it, though.

**Comment by abonander** [comment] 2016-12-14 12:39
@Drakulix Try with `multipart = "0.9.0-alpha.5"`. I've rewritten a lot of the boundary parsing and now it should handle partial reads better.

**Comment by Drakulix** [comment] 2016-12-14 17:27
Well now I get a conversion error on src/client/lazy.rs:305 and cannot compile it anymore.
I am currently stuck with rust 1.10 without updating a good amount of libraries, so if that is the problem, I might need some more time to report back.

**Comment by abonander** [comment] 2016-12-14 21:54
Yeah, I didn't realize that conversion was actually very recently added until Travis failed on Stable. I'll figure something out to fix that.

**Comment by abonander** [comment] 2016-12-14 23:19
I've published `0.9.0-alpha.6` which doesn't use that anymore.

**Comment by abonander** [comment] 2016-12-23 00:43
@Drakulix Can I get one more test run please?

**Comment by Drakulix** [comment] 2016-12-25 20:46
@abonander 
Sorry about the late reply, I am just very busy especially on the holidays right now. You will get a new log tomorrow, I promise.

**Comment by Drakulix** [comment] 2017-01-02 10:52
[hazel.txt](https://github.com/abonander/multipart/files/680657/hazel.txt)

I am deeply sorry this took so long.

**Closed** 2017-03-03 23:22 UTC
